version: '3.9'
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - mysql-db 

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./api:/var/www/html 
    ports:
      - "8084:80"
    networks:
      - laravel-network
    depends_on:
      - php-fpm
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mentes-notaveis
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge